### ISSUE TITLE
REPLACEFILE errors despite success

### ISSUE THREAD

**Issue by sicklittlemonkey** [mach-kernel/cadius#16]
Hi, thanks for your updates to this handy tool.
I was just putting a simple cross-dev script together and this puzzled me a bit:

> cadius.exe v 1.4.0 (c) Brutal Deluxe 2011-2013.
>   - Replacing file '/MERLIN16/M2#061000' :
>   Error : Can't get file from Image, File not found.
>   Error : Invalid Prodos File path '/MERLIN16/M2'.

That's a REPLACEFILE when the destination file (M2) doesn't exist.
I haven't looked at the code yet but I presume the error is from the delete.
It actually adds the file and returns a success code, but it would be nicer without errors.

Cheers,
Nick.

**Comment by mach-kernel** [comment]
@sicklittlemonkey Would you be interested in helping me maintain this? Extra hands are always useful, but especially so for code reviews & testing before release. Block device stuff is coming soon and I want to look at testing it more closely.

**Comment by sicklittlemonkey** [comment]
I can't "commit" to anything at the moment, sorry, but I'll keep an eye on things when I can. There's stuff I'd like to be doing in AppleWin that I don't have time for. Kids etc come first.
