### ISSUE TITLE
CREATEVOLUME: Invalid volume size if 143KB is specified

### ISSUE THREAD

**Issue by inexorabletash** [mach-kernel/cadius#22]
The [docs](http://brutaldeluxe.fr/products/crossdevtools/cadius/index.html) indicate:

> The Volume Size may be given in KB or in MB. Any size between 143KB and 32MB is valid (143KB, 800KB, 1600KB, 32MB, ...). 

... but specifying 143KB results in:

> Error : Invalid volume size : '143KB'.

The check in `Main.c` reads:

```c
      if(param->new_volume_size_kb <= 143 || param->new_volume_size_kb > 32768)
        param->new_volume_size_kb = 0;
```

Should that be `< 143` ?

**Comment by mach-kernel** [comment]
It appears so! Nice catch. I'll fix this one up and make a release :oncoming_police_car:

**Comment by inexorabletash** [comment]
Confirmed, thanks!

**Comment by mach-kernel** [comment]
@inexorabletash I'll make some binaries after meetings 🚔
