### ISSUE TITLE
CREATEVOLUME: Allow 140k images?

### ISSUE THREAD

**Issue by inexorabletash** [mach-kernel/cadius#28]
Follow on to #22 - why is the limit 143KB anyway?

A 5.25" floppy image is 143360 bytes but that'd be 140K the way cadius counts (140[KiB](https://en.wikipedia.org/wiki/Kibibyte)).

Should the limit be 140KB instead? This seems to work just fine.

```diff
-      if(param->new_volume_size_kb < 143 || param->new_volume_size_kb > 32768)
+      if(param->new_volume_size_kb < 140 || param->new_volume_size_kb > 32768)
```

**Comment by mach-kernel** [comment]
I will reach out to Antoine to figure out why this is the case (maybe it is error or maybe there's some motivation for it) -- but this makes sense and I don't see any reason to not make this change.

**Comment by inexorabletash** [comment]
Any word from Antoine on this, while we're doing end-of-the-year hacking?

**Comment by mach-kernel** [comment]
I sent a Facebook Message last night with a link to this thread 😸, waiting to hear back

**Comment by inexorabletash** [comment]
FWIW, another fork of cadius has this:

https://github.com/digarok/cadius/commit/e944a1c4a50d4a1ea2567afd522e63d9c600a5d5

**Comment by mach-kernel** [comment]
@inexorabletash PR is up, will merge by EOD. I never heard back from Antoine.
