### ISSUE TITLE
Cadius 1.4.4 failed to build 4am 4cade

### ISSUE THREAD

**Issue by wyatt-wong** [mach-kernel/cadius#33]
After updated Cadius to 1.4.4, I found that building 4am 4cade (https://github.com/a2-4am/4cade) failed with the following errors:

wyattwong@MacBookPro 4cade % make
mkdir -p build/X build/FX build/PRELAUNCH build/GAMEHELP
touch build/log
acme -DBUILDNUMBER=`git rev-list --count HEAD` src/4cade.a 2>build/relbase.log
acme -r build/4cade.lst -DBUILDNUMBER=`git rev-list --count HEAD` -DRELBASE=`cat build/relbase.log | grep "RELBASE =" | cut -d"=" -f2 | cut -d"(" -f2 | cut -d")" -f1` src/4cade.a
for f in src/fx/*.a; do grep "^\!to" ${f} >/dev/null && acme ${f} >> build/log || true; done
bin/buildfileinfo.sh build/FX "06" "6000" >>build/log
for f in src/prelaunch/*.a; do grep "^\!to" ${f} >/dev/null && acme ${f} >> build/log; done
for f in res/TITLE.HGR/* res/TITLE.DHGR/*; do rsync --ignore-existing build/PRELAUNCH/STANDARD build/PRELAUNCH/$(basename $f); done
cp res/blank.hdv build/"4cade.hdv" >>build/log
cp res/_FileInformation.txt build/ >>build/log
cadius ADDFILE build/"4cade.hdv" "/TOTAL.REPLAY/" "build/LAUNCHER.SYSTEM" >>build/log
rsync -aP res/PREFS.CONF build/PREFS.CONF >> build/log
bin/padto.sh 512 build/PREFS.CONF >>build/log
188+0 records in
188+0 records out
188 bytes transferred in 0.001479 secs (127121 bytes/sec)
for f in res/TITLE res/COVER res/HELP res/GAMES.CONF res/ATTRACT.CONF res/FX.CONF res/DFX.CONF build/PREFS.CONF res/CREDITS res/HELPTEXT res/DECRUNCH res/JOYSTICK res/Finder.Data res/Finder.Root; do cadius ADDFILE build/"4cade.hdv" "/TOTAL.REPLAY/" "$f" >>build/log; done
bin/buildfileinfo.sh res/TITLE.HGR "06" "4000" >>build/log
bin/buildfileinfo.sh res/TITLE.DHGR "06" "4000" >>build/log
bin/buildfileinfo.sh res/ACTION.HGR "06" "3FF8" >>build/log
bin/buildfileinfo.sh res/ACTION.DHGR "06" "3FF8" >>build/log
bin/buildfileinfo.sh res/ACTION.GR "06" "6000" >>build/log
bin/buildfileinfo.sh res/ARTWORK.SHR "06" "1FF8" >>build/log
bin/buildfileinfo.sh res/ATTRACT "04" "8000" >>build/log
bin/buildfileinfo.sh res/SS "04" "4000" >>build/log
bin/buildfileinfo.sh res/ICONS "CA" "0000" >>build/log
for f in res/TITLE.* res/ACTION.* res/ARTWORK.* res/ATTRACT res/SS res/DEMO res/TITLE.ANIMATED res/ICONS; do cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >>build/log; done
/bin/sh: line 1: 49779 Segmentation fault: 11  cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
cadius(49782,0x10a150dc0) malloc: Incorrect checksum for freed object 0x7f8f92a06db8: probably modified after being freed.
Corrupt value: 0x700000544847494e
cadius(49782,0x10a150dc0) malloc: *** set a breakpoint in malloc_error_break to debug
/bin/sh: line 1: 49782 Abort trap: 6           cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
/bin/sh: line 1: 49785 Segmentation fault: 11  cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
/bin/sh: line 1: 49791 Segmentation fault: 11  cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
/bin/sh: line 1: 49794 Segmentation fault: 11  cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
/bin/sh: line 1: 49800 Segmentation fault: 11  cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
cadius(49806,0x115c5bdc0) malloc: *** error for object 0x7fdaae706d00: pointer being freed was not allocated
cadius(49806,0x115c5bdc0) malloc: *** set a breakpoint in malloc_error_break to debug
/bin/sh: line 1: 49806 Abort trap: 6           cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
cadius(49817,0x1106bbdc0) malloc: Incorrect checksum for freed object 0x7fca9af3dfd0: probably modified after being freed.
Corrupt value: 0x7478742e6e6f69
cadius(49817,0x1106bbdc0) malloc: *** set a breakpoint in malloc_error_break to debug
/bin/sh: line 1: 49817 Abort trap: 6           cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
/bin/sh: line 1: 49820 Segmentation fault: 11  cadius ADDFOLDER build/"4cade.hdv" "/TOTAL.REPLAY/$(basename $f)" "$f" >> build/log
make: *** [Makefile:44: dsk] Error 139
wyattwong@MacBookPro 4cade %

**Comment by mach-kernel** [comment]
I'm able to reproduce the failure -- will try to roll a release with this + some other fixes soon.

**Comment by mach-kernel** [comment]
I think I got it, here is my catalog output: https://gist.github.com/mach-kernel/3bd35eb43c4f20d1124345a10a362bd6

Can you try the branch `fix-addfile-segfault` and let me know if it works?

**Comment by wyatt-wong** [comment]
> I think I got it, here is my catalog output: https://gist.github.com/mach-kernel/3bd35eb43c4f20d1124345a10a362bd6
> 
> Can you try the branch `fix-addfile-segfault` and let me know if it works?

I do NOT how to add the branch of 'fix-addfile-segfault'. I only know some basic git commands which does not include adding branch.

**Comment by mach-kernel** [comment]
Try this 😸 

```bash
git fetch origin fix-addfile-segfault
git checkout fix-addfile-segfault
make clean
make
```

**Comment by wyatt-wong** [comment]
> Try this 😸
> 
> ```shell
> git fetch origin fix-addfile-segfault
> git checkout fix-addfile-segfault
> make clean
> make
> ```

Thanks. I will try it later today and let you know.

**Comment by wyatt-wong** [comment]
Thanks the issue is fixed and I saw you already merged the branch to the master. Thanks.
