### ISSUE TITLE
v1.3 Binary Download

### ISSUE THREAD

**Issue by oliverschmidt** [mach-kernel/cadius#6]
Hi,

I'd like to use Cadius v1.3 features in a public GitHub Makefile. However, I'd rather not like my users to start with building the build tools ;-) Therefore I ask to have a v1.3 distribution like https://www.brutaldeluxe.fr/products/crossdevtools/cadius/Cadius_v1.1.zip (and have the Download link on https://www.brutaldeluxe.fr/products/crossdevtools/cadius/ updated).

Thanks,
Oliver

**Comment by mach-kernel** [comment]
Hi @oliverschmidt! 

I can absolutely do this! 1.3 [#5 is almost ready to go out](https://github.com/mach-kernel/cadius/pull/5), I am just waiting to hear back on another test run before merging it. Afterwards I can make binary releases. I will track down Antoine, he mentioned that I should ping him if I want to post the link but I forgot about it until you mentioned. 

Also: wow @ TCP/IP stack in 6502!

**Comment by oliverschmidt** [comment]
Hi,

Fist of all thanks for your very quick and positive feedback :-)

> I will track down Antoine, he mentioned that I should ping him if I want to post the link but I forgot about it until you mentioned.

;-)

> wow @ TCP/IP stack in 6502!

:-) I'm btw. contributing to @JohnMBrooks ProDOS 2.x development - and there I'd like to use Cadius: https://github.com/ProDOS-8/xHD/blob/master/client/Makefile

Regards,
Oliver

**Comment by mach-kernel** [comment]
@oliverschmidt, [this is how I did it](https://github.com/mach-kernel/mrbuffer/blob/master/assemble.sh) for my little 40 char buffer editor with Cadius. Funny that you mention, but the way I started learning 65816 assembly is by fixing the build tools 😹 to run on *nix!

**Comment by oliverschmidt** [comment]
I see. I guess we agree that this rather looks like a workaround ;-)

Talking about Makefiles... Do you see a momentum to add an option to Merlin32 to name the output filename? Maybe `-o`?

**Comment by mach-kernel** [comment]
> Talking about Makefiles... Do you see a momentum to add an option to Merlin32 to name the output filename? Maybe `-o`?

Why not? Anything that improves usability is worth it IMO.

**Comment by mach-kernel** [comment]
Added binary downloads! Will add FreeBSD binary and a Merlin32 repo tomorrow. 👍

**Comment by oliverschmidt** [comment]
> Added binary downloads!

Thanks :-)

> Will add FreeBSD binary and a Merlin32 repo tomorrow.

Cool! Maybe I'm the first to open a Merlin32 issue - that output filename thingy...
